# Generated by Django 4.2.8 on 2024-05-19 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_products_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
